[package]
name = "powersql"
version = "0.1.0"
authors = ["Dandandan <danielheres@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = "*"
walkdir = "2"
toml = "*"
serde = "*"
serde_derive = "*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
